### ISSUE TITLE
Option to not show empty workspaces symbols/buttons?

### ISSUE THREAD

**Issue by 9ineven** [d-hain/hyprland_workspace_display#1]
Hi there, first of all, thank you for this utility.

I was wondering if there is a way of omitting the --empty-symbol option, so that empty workspaces buttons wouldn't show at all?

I tried using hyprspacedp without a --empty-symbol option, but it seems to be a requirement.

Edit: I actually changed the code myself and made the empty-symbol argument optional.
I'm new to using Github, so I have no idea what I'm doing. I forked this repo and made the changes. Not sure if there was a better way of presenting the changes I made to this repo without forking it.

**Comment by d-hain** [comment]
Ok I guess I was a little too late.
But either way if you want to merge your changes in you can just make a pull request if you want.
